[book]
title = "PQC-IIoT Security Library"
authors = ["PQC-IIoT Team"]
description = "Industrial IoT Post-Quantum Cryptography Implementation Guide"
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"

[output.html]

git-repository-url = "https://github.com/doomhammerhell/pqc-iiot"
edit-url-template = "https://github.com/doomhammerhell/pqc-iiot/edit/main/docs/src/{path}"
